In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
actual = pd.read_csv('../data/raw/actual.csv')
test_df = pd.read_csv('../data/raw/data_set_ALL_AML_independent.csv')
train_df = pd.read_csv('../data/raw/data_set_ALL_AML_train.csv')

In [22]:
df1 = [col for col in train_df.columns if "call" not in col]
train_df = train_df[df1]
train_df.T.head()
train_df = train_df.T
train_df2 = train_df.drop(['Gene Description','Gene Accession Number'],axis=0)
train_df2.index = pd.to_numeric(train_df2.index)
train_df2.sort_index(inplace=True)
train_df2.head()

,0,1,2,3,4,5,6,7,8,9,...,7119,7120,7121,7122,7123,7124,7125,7126,7127,7128
1,-214,-153,-58,88,-295,-558,199,-176,252,206,...,185,511,-125,389,-37,793,329,36,191,-37
2,-139,-73,-1,283,-264,-400,-330,-168,101,74,...,169,837,-36,442,-17,782,295,11,76,-14
3,-76,-49,-307,309,-376,-650,33,-367,206,-215,...,315,1199,33,168,52,1138,777,41,228,-41
4,-135,-114,265,12,-419,-585,158,-253,49,31,...,240,835,218,174,-110,627,170,-50,126,-91
5,-106,-125,-76,168,-230,-284,4,-122,70,252,...,156,649,57,504,-26,250,314,14,56,-25

In [23]:
train_df2['cancer_type'] = list(pd.read_csv('../data/raw/actual.csv')[:38]['cancer'])
dic = {'ALL':0,'AML':1}
train_df2.replace(dic,inplace=True)

,0,1,2,3,4,5,6,7,8,9,...,7120,7121,7122,7123,7124,7125,7126,7127,7128,cancer_type
1,-214,-153,-58,88,-295,-558,199,-176,252,206,...,511,-125,389,-37,793,329,36,191,-37,0
2,-139,-73,-1,283,-264,-400,-330,-168,101,74,...,837,-36,442,-17,782,295,11,76,-14,0
3,-76,-49,-307,309,-376,-650,33,-367,206,-215,...,1199,33,168,52,1138,777,41,228,-41,0
4,-135,-114,265,12,-419,-585,158,-253,49,31,...,835,218,174,-110,627,170,-50,126,-91,0
5,-106,-125,-76,168,-230,-284,4,-122,70,252,...,649,57,504,-26,250,314,14,56,-25,0
6,-138,-85,215,71,-272,-558,67,-186,87,193,...,1221,-76,172,-74,645,341,26,193,-53,0
7,-72,-144,238,55,-399,-551,131,-179,126,-20,...,819,-178,151,-18,1140,482,10,369,-42,0
8,-413,-260,7,-2,-541,-790,-275,-463,70,-169,...,629,-86,302,23,1799,446,59,781,20,0
9,5,-127,106,268,-210,-535,0,-174,24,506,...,980,6,177,-12,758,385,115,244,-39,0
10,-88,-105,42,219,-178,-246,328,-148,177,183,...,986,26,101,21,570,359,9,171,7,0
11,-165,-155,-71,82,-163,-430,100,-109,56,350,...,642,32,137,-81,672,208,25,116,-62,0
12,-67,-93,84,25,-179,-323,-135,-127,-2,-66,...,224,60,194,-10,291,41,8,-2,-80,0
13,-92,-119,-31,173,-233,-227,-49,-62,13,230,...,583,3,530,-39,696,302,24,74,-11,0
14,-113,-147,-118,243,-127,-398,-249,-228,-37,113,...,440,52,229,-4,431,269,8,163,-22,0
15,-107,-72,-126,149,-205,-284,-166,-185,1,-23,...,722,20,332,-5,195,59,31,116,-18,0
16,-117,-219,-50,257,-218,-402,228,-147,65,67,...,631,-26,455,-62,736,445,42,246,-43,0
17,-476,-213,-18,301,-403,-394,-42,-144,98,173,...,1215,127,255,50,1701,1109,61,526,-83,0
18,-81,-150,-119,78,-152,-340,-36,-141,96,-55,...,573,-57,694,-19,636,205,17,127,-13,0
19,-44,-51,100,207,-146,-221,83,-198,34,-20,...,397,-48,1939,-18,538,90,-50,333,-24,0
20,17,-229,79,218,-262,-404,326,-201,6,469,...,1020,-110,209,-51,1435,255,53,545,-16,0
21,-144,-199,-157,132,-151,-347,-118,-24,126,-201,...,595,-12,36,26,208,113,-8,22,-22,0
22,-247,-90,-168,-24,-308,-571,-170,-224,124,-117,...,402,57,253,-52,1010,405,19,270,-27,0
23,-74,-321,-11,-36,-317,-499,-138,-119,115,-17,...,1058,140,176,-22,617,336,9,243,36,0
24,-120,-263,-114,255,-342,-396,-412,-153,184,-162,...,725,13,249,1,646,391,81,203,-94,0
25,-81,-150,-85,316,-418,-461,-66,-184,164,-5,...,392,8,506,24,1034,69,24,807,-41,0
26,-112,-233,-78,54,-244,-275,-479,-108,136,-86,...,678,77,2527,-36,838,313,21,145,-19,0
27,-273,-327,-76,81,-439,-616,419,-251,165,350,...,816,45,62,-71,583,677,-1,208,10,0
28,-4,-116,-125,241,-191,-411,-31,-240,150,24,...,755,-23,573,42,987,279,22,662,-46,1
29,15,-114,2,193,-51,-155,29,-105,42,524,...,492,54,277,-13,279,51,6,2484,-2,1
30,-318,-192,-95,312,-139,-344,324,-237,105,167,...,737,63,472,33,737,227,-9,371,-31,1
31,-32,-49,49,230,-367,-508,-349,-194,34,-56,...,592,57,215,-22,588,361,-26,133,-32,1
32,-124,-79,-37,330,-188,-423,-31,-223,-82,176,...,938,-15,433,-2,1170,284,39,298,-3,1
33,-135,-186,-70,337,-407,-566,-141,-315,206,321,...,634,-58,375,-23,2315,250,-12,790,-10,1
34,-20,-207,-50,101,-369,-529,14,-365,153,29,...,1009,-55,139,-57,834,557,-12,335,-65,1
35,7,-100,-57,132,-377,-478,-351,-290,283,247,...,336,-45,170,12,752,295,28,1558,-67,1
36,-213,-252,136,318,-209,-557,40,-243,119,-131,...,1653,67,486,-88,1293,342,26,246,23,1
37,-25,-20,124,325,-396,-464,-221,-390,-1,358,...,486,-32,334,35,1733,304,12,3193,-33,1
38,-72,-139,-1,392,-324,-510,-350,-202,249,561,...,1121,102,330,-112,1567,627,21,2520,0,1

Sparse Logistic Regression

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(train_df2.drop('cancer_type',axis=1))
y = train_df2['cancer_type']

In [32]:
y_fit = y.to_numpy().ravel().astype(int)
logreg = LogisticRegression(
    l1_ratio=1,           # pure L1
    solver='saga', C=0.08,
    max_iter=10000, tol=1e-4, random_state=0
).fit(X_std, y_fit)

print('n_iter:', logreg.n_iter_)
print('nonzero coefs:', np.sum(logreg.coef_ != 0))

print(logreg.n_iter_)   # if this equals max_iter, it did NOT converge

logreg.predict(X_std)

score = logreg.score(X_std, y_fit)
print('score:',score)
coef = logreg.coef_.ravel()
nonzero_idx = np.where(coef != 0)[0]
print('nonzero coefs:', len(nonzero_idx))

n_iter: [2546]
nonzero coefs: 3
[2546]
score: 0.7105263157894737
nonzero coefs: 3